### ISSUE TITLE
The ViFi step 4|5 google link point to error

### ISSUE THREAD

**Issue by shengzhulst** [sara-javadzadeh/FastViFi#1]
Dear Sara
Can you fix the ViFi installation step 4|5 google link:  https://drive.google.com/open?id=0ByYcg0axX7udUDRxcTdZZkg0X1k which assist to build $AA_DATA_REPO?
The fastViFi is totally dependent on ViFi and without knowing the data stored in this link I cannot make the ViFi pipeline works.

**Comment by sara-javadzadeh** [comment]
Hi Shiting,

Thank you for reaching out and pointing out the issue. I've pushed a commit
with updated links. Please go ahead and test it out and keep me posted in
case of any issues.

Best,
Sara

**Comment by sara-javadzadeh** [comment]
Fixed in commit dc800bfa0adf59a8231fa5f1123113bea1446dcf on ViFi repository:
https://github.com/sara-javadzadeh/ViFi/commit/dc800bfa0adf59a8231fa5f1123113bea1446dcf
