### ISSUE TITLE
output interpretation HIV

### ISSUE THREAD

**Issue by antoine4ucsd** [sara-javadzadeh/FastViFi#15]
Hello
First, I would like to thank you for developping this promising and much needed pipeline!
I am mostly interested in HIV integration so I tried to adapt FastViFi accordingly.

I started by creating 
- set of hiv viral sequences
```
build_references.sh input.fas oupath hiv path_to/ViFi/scripts/
cat $AA_DATA_REPO//GRCh38/hg38full.fa $REFERENCE_REPO/hiv/input.fas > $REFERENCE_REPO/hiv/grch38_hiv.fas
bwa index $REFERENCE_REPO/hiv/grch38_hiv.fa
```
it looks like that
![image](https://github.com/sara-javadzadeh/FastViFi/assets/18502631/98c4ad05-6380-40d1-b2a5-648f394af32f)

- prepare kraken db (not sure I did it right, especially related to kmer) with addition of my own set of hiv seq (input.fas above)
Here I put 22 and 25 in the name but this is confusing since I used default setting for kmer
```
kraken2-build --download-taxonomy --db Kraken2StandardDB_k_25_hiv_hg
kraken2-build --download-library viral --db Kraken2StandardDB_k_25_hiv_hg
kraken2-build --download-library human --db Kraken2StandardDB_k_25_hiv_hg
kraken2-build --add-to-library /references/",allfiles[i]," --db Kraken2StandardDB_k_25_hiv_hg # within a loop
kraken2-build --build   --threads 24 --db Kraken2StandardDB_k_25_hiv_hg
```
and viral only
```
kraken2-build --download-taxonomy --db Kraken2StandardDB_k_22_hiv
kraken2-build --download-library viral --db Kraken2StandardDB_k_22_hiv
kraken2-build --add-to-library /references/",allfiles[i]," --db Kraken2StandardDB_k_25_hiv_hg # within a loop
kraken2-build --build   --threads 24 --db Kraken2StandardDB_k_22_hiv
```

I got these db now
![image](https://github.com/sara-javadzadeh/FastViFi/assets/18502631/1331a6d2-685f-41c1-91a6-92ad73fc49b5)

then I ran  run_kraken_vifi_container.py  with docker  and --skip-bwa-filter on my set of paired fastq  
(ps --threads does not seem to be taken into account???)
it takes a while to get these outputs
![image](https://github.com/sara-javadzadeh/FastViFi/assets/18502631/12f36a31-805b-4558-a6d6-1b71ea4a6e0a)

there are reads in trans.bam BUT output_hiv.clusters.txt is empty
could you help me interpreting/adjusting ? should I build db with different kmer? suggestions? other options? skip skip_kraken_filters? (this latest option does not seem to be considered either ,same as for --threads)

I am attaching a few output files 

looking forward to hearing from you!
thank you 

ps: it works well for hpv and I get the cluster txt as in your example
ps2: if you have experience working with HIV and already created bd, maybe I can try with yours?

[outputs.zip](https://github.com/sara-javadzadeh/FastViFi/files/15458529/outputs.zip)

**Comment by sara-javadzadeh** [comment]
Hi Antoine,

We have been in touch over email in the past couple of weeks. So I haven't been updating the GitHub issue thread. I did not have experience with HIV before.

I pushed an updated version of both ViFi and FastViFi to resolve the issues regarding the clustering script. I also fixed the issue on the thread count not being set correctly.

**Comment by antoine4ucsd** [comment]
thank you!
