### ISSUE TITLE
ViFi pipeline has warning messages and test dataset can't generate expected results

### ISSUE THREAD

**Issue by shengzhulst** [sara-javadzadeh/FastViFi#2]
Hi Sara,
I did meet another problem when I tested the ViFi pipeline, I used the most updated docker version of ViFi and run_ViFi.py script. The pipeline works well on the beginning steps and It seems like fail at the step run the merge_viral_reads.py. I check the reduced.csv and find it's empty. I am using the last line command in the setup_linux_mac.sh and set up everything well. Here I stick the error message here and can you help me check what's happening?  
![image](https://user-images.githubusercontent.com/31368777/140377247-cf4f2ddf-bdba-40e1-b48b-94a1b57573c7.png)

**Comment by sara-jvz** [comment]
Hi Shiting,

Thanks for bringing this up. In order to locate the problem, could you please provide the following?
- The entire output. The screenshot seems to be be missing part of the output. Sharing the output in text format could be the easiest.
- Did you set the environment variables $AA_DATA_REPO and $REFERENCE_REPO? If possible, could you please share the output of these?
`echo $AA_DATA_REPO`
and
`echo $REFERENCE_REPO`

**Comment by shengzhulst** [comment]
Hi Sara,
Sorry to reply a little late, I post the output.txt(stdoutput) and output.log(stderr) here. And the command I run is python $VIFI_DIR/scripts/run_vifi.py --cpus 2 --hmm_list /shiting/ViFi_reference/viral_data/${virus}/hmms/hmms.txt -f $VIFI_DIR/test/data/test_R1.fq.gz -r $VIFI_DIR/test/data/test_R2.fq.gz -o $VIFI_DIR/tmp/docker/ --docker --viral_reference_dir $REFERENCE_REPO --hg_data_dir $AA_DATA_REPO --vifi_dir $VIFI_DIR 2>&1 >output.log
[ViFi_output.log](https://github.com/sara-javadzadeh/FastViFi/files/7506739/ViFi_output.log)
[ViFi_output.txt](https://github.com/sara-javadzadeh/FastViFi/files/7506740/ViFi_output.txt)

For the `ls $AA_DATA_REPO`, `ls $REFERENCE_REPO`I have a picture here.
![image](https://user-images.githubusercontent.com/31368777/140973568-a0606293-6a4e-4f61-9378-97f25c7bca06.png)

**Comment by sara-javadzadeh** [comment]
Hi Shiting,

Thanks for providing the info.
Looks like the file 'reference.txt' in 'data_repo' directory is missing.
I updated the ViFi repository installation script and README to create the file as a step of the installation (https://github.com/sara-javadzadeh/ViFi/commit/26a6fb8c1f33eece25d64cd83e3cc9c7ecdac3fe)
Please remove the 'data_repo' directory and repeat the installation steps.

For any other problems with ViFi, I would appreciate it if you could open an issue on the ViFi repository (https://github.com/sara-javadzadeh/ViFi). It would be much easier to link the issues and fix commits on the same repo. Also, others can follow the ViFi installation issues easier on the ViFi repository.

Thanks,
Sara
