### ISSUE TITLE
human reference file not existent

### ISSUE THREAD

**Issue by aflocon** [sara-javadzadeh/FastViFi#6]
Hi,
We wanted to use your software, but the link to the human reference file isn't working anymore. Could you please update it?
here is the link: https://drive.google.com/file/d/1il10KUxJ5Q5JvR5pHJB4GUMBlBPgTjrj/view?usp=sharing 

Or is there another solution?
Thank you in advance
Albane

**Comment by sara-javadzadeh** [comment]
Hi Albane,

Thanks for reaching out. The link is updated in the README.md file. Copying the link here:
[https://drive.google.com/file/d/1XBZbwgcV1n2AWWAyt2RWfSKKxzssRFBo/view?usp=share_link](https://drive.google.com/file/d/1XBZbwgcV1n2AWWAyt2RWfSKKxzssRFBo/view?usp=share_link)
Please let me know if you still have access issues.

Best,
Sara

**Comment by aflocon** [comment]
Hi,
Thank you very much for your answer. We can access to the file now, it's
perfect!
Best regards,
Albane


Le ven. 9 déc. 2022 à 22:51, Sara Javadzadeh ***@***.***> a
écrit :

**Comment by sara-javadzadeh** [comment]
Great! Closing the issue.
