### ISSUE TITLE
Use the whole exome sequencing?

### ISSUE THREAD

**Issue by xiasijian** [sara-javadzadeh/FastViFi#8]
Hi, sara.
I have no idea whether the software FastViFi is used for the NGS data from whole exome sequencing.

Best wishes.

**Comment by xiasijian** [comment]
![image](https://user-images.githubusercontent.com/39158528/223988111-ceea05cd-1f9f-4013-accc-2f418f5570de.png)

Why does the kraken_datasets.tar.gz only contains hpv database?

**Comment by sara-javadzadeh** [comment]
Hi Sijian,

Yes, the kraken database including Kraken indexes are only available for HPV. What virus are you looking into?
I can share databases for hepatitis B virus (HBV), hepatitis C virus (HCV) and Epstein–Barr virus (EBV). If you are looking into other viruses, I have some instructions on how to build custom kraken databases in the [FastViFi readme](https://github.com/sara-javadzadeh/FastViFi#custom-kraken-datasets). I'm available to answer any questions for building custom databases in case you had any trouble.

Best,
Sara

**Comment by xiasijian** [comment]
Hi Sara,

Thanks for your reply. If it is convenient for you, can you share the database for Epstein–Barr virus (EBV)? If yes, I will be deeply grateful for you🤞.

Best wishes
Sijian

**Comment by sara-javadzadeh** [comment]
Sounds good. I'm compressing the EBV indexes. I will share a Google Drive link after compression and uploading.

**Comment by xiasijian** [comment]
Thanks a lot🌹

**Comment by sara-javadzadeh** [comment]
Hi Sijian,
[Here's the link](https://drive.google.com/file/d/1QYn5lDWjvhtIWCrwmzDc_1fy8ANrXWz1/view?usp=sharing) for downloading Kraken indexes for EBV. Let me know if you had any problems when using it.

**Comment by xiasijian** [comment]
Great! Thanks for your efforts. 😊
